### ISSUE TITLE
Emoticons support for Label

### ISSUE THREAD

**Issue by GV3** [feathersui/feathersui-starling#1321]
A few months ago I came across this thread ( http://forum.starling-framework.org/topic/emoticons-support-for-label) and I wonder today if a solution has been implemented, or if it's planned to support the display of the native font emoticons in a Label.

**Comment by joshtynjala** [comment]
This is completely controlled by the runtime. There's nothing that I can do to improve support on the Feathers side.

**Comment by GV3** [comment]
Here the link to the bug report or feature request at the Adobe bug base:
 
[Bug#4184369 - Emoji colors wrongly rendered in 'direct' mode](https://bugbase.adobe.com/index.cfm?event=bug&id=4184369)
 
Unsolved and open for votes at the time of this post (AIR SDK 23.0.0.257)
