### ISSUE TITLE
Component/Feature request: StackList 

### ISSUE THREAD

**Issue by GV3** [feathersui/feathersui-starling#1385]
I'm now working on developing a List with a StackLayout, where the itemRenderer stack over each other (Like on Tinder and other Apps) and where the items are processed by swiping them to any of the four sides.

I think this would be a great new component or Layout for the List component.

I would also appreciate any opinions, ideas or guidance you would have. To know if you think this could be something that will be incorporated in the Feathers library, and about the approach am taking right now. 

Best regards

**Comment by joshtynjala** [comment]
The easiest approach is probably to create a custom component that keeps track of the currently visible item and keeps the next at a lower depth. When a swipe is finished, swap depths and repopulate the old item. I wouldn't use any kind of scrolling component. Just drag an item with TouchEvents. Take a look at how the Drawers component detects when a drag starts. The code should be pretty similar.

**Comment by GV3** [comment]
Thanks for the Advice! I'll take a look into the Drawers component.

From 1 to 10 how interested are you in creating this component at any time in Feathers?

If you are interested I'll try to build it as a component extending the Feathers library and following as much as possible the methods used in Feathers, such as commitData and ListCollection, and request a pull for you to review it once finished.

**Comment by joshtynjala** [comment]
While I don't think I'm interested in building it myself, I'd be happy to accept a pull request and include it!

Please try to follow the [coding conventions](http://feathersui.com/help/coding-conventions.html). :smile:

**Comment by GV3** [comment]
Coding conventions set!

I took the liberty to create a IntelliJ IDEA coding-style-scheme following the coding conventions you describe.

Please do review it and fell free to include it in the link.
[Feathers-Intellij-CodeStyleScheme.xml.zip](https://github.com/BowlerHatLLC/feathers/files/278414/Feathers-Intellij-CodeStyleScheme.xml.zip)
