### ISSUE TITLE
bidirectional text component for bitmap fonts

### ISSUE THREAD

**Issue by HendrixString** [feathersui/feathersui-starling#1515]
hi @joshtynjala, I implemented this a while back,
a complete implementation of the Bidi algorithm (Revision 31) used 
for bitmap fonts. It works well
https://github.com/HendrixString/Starling-Bidi-TextField

was wondering, if you would like to include a modified version of this in Feathers?

all the best
T

**Comment by joshtynjala** [comment]
Thanks! I'll take a look when I get a chance.

**Comment by HendrixString** [comment]
cool, have a look at this too if you have time
https://github.com/HendrixString/Falcon/tree/master/src/com/hendrix/feathers/controls/flex

this is a prototype written back then on top of feathers to enable Flex-like components,
something that I really wanted in the early Feathers releases.
