### ISSUE TITLE
Scroller: specify exactly which edges may be elastic (hasElasticEdges currently always affects all edges)

### ISSUE THREAD

**Issue by GV3** [feathersui/feathersui-starling#1525]
Hi Josh,

I'll go straight to the prominent real world example, so that you see a real scenario where this could be useful.

Instagram > Chat > Single Conversation > Pull the message item to the left

I know that in this specific example the message items can be pulled to the left and not the whole list. But I'm sure more than one would profit from being able to decide what border/edge should be Elastic, and if we want to be fancy, be able to set different elasticity factors to each edge.

I imagine the code like this: 

` hasElasticEdges = true; // valid still`
` hasElasticEdges = false; // valid still`
`hasElasticEdges = RealtivePosition.TOP + ',' + RealtivePosition.BOTTOM + ',' + RelativePosition.RIGHT; // New 
`

Thanks for considering it

**Comment by joshtynjala** [comment]
I sent a message to my wife to test, and she said the same gesture is available in the iOS Messages app. :smile:
