### ISSUE TITLE
TextInput width changes from focus in / focus out - Android Only

### ISSUE THREAD

**Issue by urthling** [feathersui/feathersui-starling#1812]
Hey Josh,

Is this an issue with the runtime?

Feathers 4.1.1 / TextInput 

Image 1 = Editing the text (both are good)
Image 2 = Focused out (issue on Android)

Note that on the Android device, when focussed out, the text width is less than the actual width of the field -- right padding is set to 0, so iOS is rendering as one would expect.  In a multiline TextInput, the text wraps too soon - wrong width.

![ios_android_inconsistent_textinput](https://user-images.githubusercontent.com/6290921/135114652-7902bd60-9e1d-4c36-8590-ca8fdb7fc49f.png)

**Comment by joshtynjala** [comment]
Interesting. I don't know what would cause that.

**Comment by urthling** [comment]
I've replicated this in a simple project and determined the cause -- when creating the sample project, I first used a basic rectangle and scale factor of 2 and I couldn't replicate the issue.

However, in my project is using the recommended screen setup: https://raw.githubusercontent.com/Gamua/Starling-Framework/master/samples/scaffold_mobile/src/utils/ScreenSetup.as

Once I added this to the test project, then sure enough, I was able to replicate. This is the setup I used that doesn't account for the devices actual scale and uses a value of 2 -- and everything works as expected, no truncation.
```
this._starling 					= new Starling(BlackScreenTest 		, this.stage, new Rectangle(0, 0, this.stage.fullScreenWidth, this.stage.fullScreenHeight));
this._starling.stage.stageWidth 		= this.stage.fullScreenWidth/2;
this._starling.stage.stageHeight 		= this.stage.fullScreenHeight/2;
```
As you know, ScreenSetup calculates the actual scale from the device:
```
var screen 			:ScreenSetup 	= new ScreenSetup(this.stage);
this._starling 					= new Starling(BlackScreenTest 		, this.stage, screen.viewPort)
this._starling.stage.stageWidth 		= screen.stageWidth;
this._starling.stage.stageHeight 		= screen.stageHeight;
```

In my project, in order to place everything on the screen at exactly the same position, I assume a width of 416 and height of 736, then I scale everything up or down in order to fit on screen.

For example, the far right of the screen is always sX(416) -- I allow for taller/shorter devices by calculating the extra/reduced height, then the very bottom of the screen is sY(736) + bufferedHeight.  This allows me specify exact x,y positioning, and have a consistent look across all screen sizes, font sizes etc. Everything looks great from tiny Android devices through large screens -- the only issue is what is now happening on Android devices

So, the TextInput I apply a scale like this:

```
textInput1.scaleX 				= this.coreModel.scaleFactorX;
textInput1.scaleY 				= this.coreModel.scaleFactorY;

```

I've opened this issue on Adobe-Runtime-Support but I wanted to ask you if this could in fact be something to do with Feathers?  I'm assuming something like this is going to be a runtime issue and not Feathers but what do you think?

**Comment by joshtynjala** [comment]
@urthling Are `scaleFactorX` and `scaleFactorY` equal, or are they different values?

**Comment by urthling** [comment]
They're slightly different.. On my Samsung Note 8 they are:
```

0.8653846153846154
0.8654891304347826

```

**Comment by joshtynjala** [comment]
Those two scale factors seem close enough that they wouldn't cause any noticeable issues. If they were more different, that might have caused issues. However, that usually involves the editable text being out of bounds, rather than the texture/bitmap snapshot being clipped.

It may simply be that setting `scaleX` and `scaleY` is enough to cause this issue. `StageText` does not offer the ability to scale because it's not a real display object, and that's what `TextInput` uses in its default text editor, `StageTextTextEditor`. It might be worth trying `TextFieldTextEditor` instead, especially considering that you mentioned that `TextArea` is fine. `TextArea` uses `TextField` instead of `StageText` by default.

**Comment by urthling** [comment]
Ah, interesting, I'll give it a go, thank you!

**Comment by urthling** [comment]
Ah, thank you so much for your support Josh! That was it -- with a few tweaks (changes in where to set `softKeyboard` etc) problem has been resolved.

Interesting how iOS doesn't have this issue -- a ticket is open with Harman at the moment, will be interesting to see if they can offer a solution to this by allowing `StageText` to scale

Once again, thank you!!
