### ISSUE TITLE
TextInput: Using `textEditorFactory` with `TextBlockTextEditor` and double-clicking to select all will not accept any key input afterwards

### ISSUE THREAD

**Issue by 2jfw** [feathersui/feathersui-starling#1829]
For a `TextInput` and when using `textEditorFactory` with a  `TextBlockTextEditor` and double-clicking text input to select all will not accept any key input afterwards.

**Will work:**

```
var tf : TextInput = new TextInput();
tf.text = "DoubleClickMe";
tf.width = tf.height = 300;

addChild(tf);
```

**Will not work after double clicking and typing:**

```
var tf : TextInput = new TextInput();
tf.text = "DoubleClickMe";
tf.width = tf.height = 300;

tf.textEditorFactory = function () : ITextRenderer {
        var textRenderer : TextBlockTextEditor = new TextBlockTextEditor();
        
        return textRenderer;
};

addChild(tf);
```

**Comment by 2jfw** [comment]
- Manually selecting the text range with mouse (mouse down + move) will work in both cases
- Using shift + key arrow left right to select will work
- Using POS1 or END after double clicking will also not work

Tracked down to a missing native textfield focus in event not triggering

**Comment by joshtynjala** [comment]
I can reproduce this issue. It appears that stage.focus becomes null after double-clicking the text editor, for some reason. It may be something in the focus manager is clearing the focus when it should not.

FYI – feathersui-starling is not under active development anymore, so it's unlikely that I will spend further time investigating or working on a fix.

**Comment by joshtynjala** [comment]
Yes, I will review and merge PRs as time permits.

**Comment by 2jfw** [comment]
Sounds good, thanks!

Meanwhile, posting a short and **dirty** workround for this issue is (manually clearing and re-setting focus):

```
private function onTouch(event : TouchEvent) : void
{
	var touch : Touch = event.getTouch(this);

	if (touch.phase == TouchPhase.ENDED)
	{
		if (event.target is TextBlockTextEditor && touch.tapCount > 1)
		{
		// workaround for double click not working when then trying to type
		_textInput.clearFocus();
		_textInput.setFocus();
		}
	}
}
```


			if (touch.phase == TouchPhase.BEGAN)
			{
				if (event.target == _mainGroup)
				{
					Starling.current.nativeStage.nativeWindow.startMove();
				}
			}
			else if (touch.phase == TouchPhase.ENDED)
			{
				if (event.target is TextBlockTextEditor && touch.tapCount > 1)
				{
					// workaround for double click not working when then trying to type
					_textInput.clearFocus();
					_textInput.setFocus();
				}
			}
		}
